apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce # Choose appropriate access mode based on your use case (should match PV)
  storageClassName: aws-efs # Use the same storage class as defined in PV
  resources:
    requests:
      storage: 10Gi # Requested storage size, should match or be less than PV capacity
