apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-pv
spec:
  capacity:
    storage: 10Gi # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Choose appropriate access mode based on your use case
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs # Use a storage class that maps to EBS
  awsElasticBlockStore:
    volumeID: vol-08dd81b50b8401725 # Replace this with your EBS volume ID
    fsType: ext4 # Filesystem type, ext4 is commonly used

