apiVersion: v1
kind: Service
metadata:
  name: sql01
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
