apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: nginx-service
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /usr/share/nginx/html  # Mount the volume to nginx HTML directory
  volumeClaimTemplates:
    - metadata:
        name: nginx-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "gp2"  # Replace with the appropriate storage class
        resources:
          requests:
            storage: 1Gi  # Adjust the storage size as needed
